# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source
COPY . ./

# Expose port for HTTP transport (Smithery uses 8081)
EXPOSE 8081

# Default command - run HTTP server
CMD ["node", "src/http-server.js"]
