# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy application source
COPY . .

# Ensure the start script is executable
RUN chmod +x start-server.sh

# Start the MCP server via stdio
ENTRYPOINT ["./start-server.sh"]
