# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for JW MCP Server
FROM node:lts-alpine

# Create app directory
env APP_DIR=/usr/src/app
RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR

# Install app dependencies
# Copy package.json and package-lock.json
COPY package*.json ./
# Skip prepare to avoid unexpected scripts
RUN npm install --ignore-scripts --production

# Bundle app source
COPY . $APP_DIR

# Ensure start-server.sh is executable
RUN chmod +x ./start-server.sh

# Default command
ENTRYPOINT ["node", "src/index.js"]
